### ISSUE TITLE
How to use your model for other data sets?

### ISSUE THREAD

**Issue by Jackson-zhao97** [v1xerunt/StageNet#7]
Hello, after reading the StageNet model, I am very interested. So, if I want to use it for modeling the sequence of access data composed of 11 variables with unequal intervals. May I ask which parts of the model you mentioned to change? 

I'm looking forward to your answer, thanks.

**Comment by v1xerunt** [comment]
Hi, since the train.py code is customized for the MIMIC dataset, I suggest you to write your own data preprocessing pipeline and use the model.py code. You need to provide three parameters to the model.forward() func: (1) 'input' is the input data tensor, in your case the shape is [batch_size, timestep], 11; (2) 'time' is the interval between each timestep with shape [batch_size, timestep]; (3) device indicates if you want to use cuda to train the model.

**Comment by Jackson-zhao97** [comment]
I appreciate you kind reply to my question. I‘ll try it!!!
